### ISSUE TITLE
Consider adding lifecycle events 

### ISSUE THREAD

**Issue by Nevraeka** [mikeal/zcomponent#5]
I was thinking that `onConnected`, `onDisconnected`, `attributeChangedCallback`, `onAdoptedCallback` and possibly observed attributes &/or attribute marshaling, attribute reflection to properties might be helpful to scale this. I do appreciate the simplicity in design though and maybe these would clutter the base component. Thoughts?

As an aside check out [The Elix Project](https://github.com/elix/elix). They have a set of great mixins and use JS Symbols to store private properties in classes.  It's much closer to the platform than most libraries I have seen. That said,  it is a library & NOT a single module so it may not be the approach you desire.

It's great to see a new and different approach to WC's like this one. Thank you for your hard work in open source @mikeal

**Comment by mikeal** [comment]
I've started to move past this project. Check out these libraries:

* [rza](https://github.com/mikeal/rza)
* [gza](https://github.com/mikeal/gza)

**Comment by mikeal** [comment]
Deprecating this project.
